apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-gke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-gke
  template:
    metadata:
      labels:
        app: ml-gke
    spec:
      containers:
      - name: ml-gke-app
        # Replace $LOCATION with your Artifact Registry location (e.g., us-west1).
        # Replace $PROJECT_ID with your project ID.
        image: europe-west6-docker.pkg.dev/landmark-classifier/app-repo-gke/flask-app-gke:latest
        # This app listens on port 8080 for web traffic by default.
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
        resources:
          requests:
            memory: "4Gi"
            cpu: "2"
            ephemeral-storage: "1Gi"
          limits:
            memory: "4Gi"
            cpu: "2"
            ephemeral-storage: "1Gi"